import { PrismaClient, Role, Sentiment, FeedbackStatus } from "@prisma/client";
import bcrypt from "bcryptjs";

const prisma = new PrismaClient();

// Helper to generate past dates within the last 60 days
function getPastDate(daysAgo: number, hoursAgo = 0): Date {
  const d = new Date();
  d.setDate(d.getDate() - daysAgo);
  d.setHours(d.getHours() - hoursAgo);
  return d;
}

async function main() {
  console.log("🌱 Starting Project LOOP Phase 3 Foundation Seed (120+ Demo Dataset)...");

  // 1. Clean up existing demo data deterministically
  await prisma.feedbackTheme.deleteMany();
  await prisma.embedding.deleteMany();
  await prisma.feedback.deleteMany();
  await prisma.theme.deleteMany();
  await prisma.report.deleteMany();
  await prisma.user.deleteMany();
  await prisma.workspace.deleteMany();

  // 2. Create Primary Demo Workspace (Acme SaaS)
  const acmeWorkspace = await prisma.workspace.create({
    data: {
      name: "Acme SaaS (Demo Workspace)",
    },
  });
  console.log(`✓ Created Primary Workspace: ${acmeWorkspace.name} (${acmeWorkspace.id})`);

  // Create Secondary Workspace for verifying tenant isolation
  const betaWorkspace = await prisma.workspace.create({
    data: {
      name: "Beta Retail (Tenant Isolation Test)",
    },
  });
  console.log(`✓ Created Secondary Workspace: ${betaWorkspace.name} (${betaWorkspace.id})`);

  // 3. Create Demo Users across the 3 mandatory RBAC roles
  const salt = bcrypt.genSaltSync(10);
  const passwordHash = bcrypt.hashSync("DemoPass123!", salt);

  const adminUser = await prisma.user.create({
    data: {
      name: "Alice Admin",
      email: "admin@loop.demo",
      passwordHash,
      role: Role.ADMIN,
      workspaceId: acmeWorkspace.id,
    },
  });

  const analystUser = await prisma.user.create({
    data: {
      name: "Bob Analyst",
      email: "analyst@loop.demo",
      passwordHash,
      role: Role.ANALYST,
      workspaceId: acmeWorkspace.id,
    },
  });

  const viewerUser = await prisma.user.create({
    data: {
      name: "Charlie Viewer",
      email: "viewer@loop.demo",
      passwordHash,
      role: Role.VIEWER,
      workspaceId: acmeWorkspace.id,
    },
  });

  // Secondary workspace admin
  await prisma.user.create({
    data: {
      name: "Retail Admin",
      email: "retail.admin@loop.demo",
      passwordHash,
      role: Role.ADMIN,
      workspaceId: betaWorkspace.id,
    },
  });

  console.log(`✓ Created Demo Users:`);
  console.log(`   - ADMIN:   ${adminUser.email} (Password: DemoPass123!)`);
  console.log(`   - ANALYST: ${analystUser.email} (Password: DemoPass123!)`);
  console.log(`   - VIEWER:  ${viewerUser.email} (Password: DemoPass123!)`);

  // 4. Create Core Themes for Acme SaaS
  const themeData = [
    { key: "onboarding", name: "Onboarding & Navigation", description: "Sign-up wizard, workspace setup, and invite UX", color: "#3B82F6" },
    { key: "billing", name: "Billing & Invoicing", description: "Invoices, payment processing, subscription tiers, and pricing", color: "#EF4444" },
    { key: "performance", name: "Performance & Reliability", description: "Page load speed, timeouts, and system uptime", color: "#F59E0B" },
    { key: "security", name: "Security & SSO Access", description: "SAML SSO, RBAC permissions, 2FA, and audit logging", color: "#8B5CF6" },
    { key: "mobile", name: "Mobile App Experience", description: "iOS & Android responsiveness, biometrics, and push alerts", color: "#10B981" },
    { key: "integrations", name: "Integrations & API", description: "Webhooks, Zapier, Salesforce CRM sync, and REST API", color: "#06B6D4" },
    { key: "analytics", name: "Reporting & Analytics", description: "Data visualizations, CSV exports, and VoC summary digests", color: "#EC4899" },
    { key: "features", name: "Feature Requests", description: "User requested enhancements and workflow customizations", color: "#6366F1" },
  ];

  const themes: Record<string, string> = {};
  for (const t of themeData) {
    const created = await prisma.theme.create({
      data: {
        name: t.name,
        description: t.description,
        color: t.color,
        workspaceId: acmeWorkspace.id,
      },
    });
    themes[t.key] = created.id;
  }
  console.log(`✓ Created ${Object.keys(themes).length} Themes for Acme SaaS`);

  // Themes for Beta Retail (for isolation testing)
  const retailTheme = await prisma.theme.create({
    data: {
      name: "Store POS & Checkout",
      description: "In-store cash register and barcode scanner hardware",
      color: "#14B8A6",
      workspaceId: betaWorkspace.id,
    },
  });

  // 5. Seed 125+ Realistic Feedback Items across 5 Channels
  // Dataset definitions with channels, content, customerLabels, sourceRefs, sentiments, scores, status, and theme associations
  const rawDataset = [
    // --- SUPPORT TICKETS (30 items) ---
    {
      channel: "SUPPORT_TICKET",
      content: "Billing page keeps timing out when I try to download our monthly VAT invoice. Error code: 504 Gateway Timeout.",
      customerLabel: "Enterprise Tier",
      sourceRef: "ZD-10492",
      sentiment: Sentiment.NEG,
      sentimentScore: -0.85,
      status: FeedbackStatus.NEW,
      daysAgo: 2,
      themeKeys: ["billing", "performance"],
    },
    {
      channel: "SUPPORT_TICKET",
      content: "Onboarding took forever — I couldn't figure out how to invite my team members from the settings view.",
      customerLabel: "Mid-Market",
      sourceRef: "ZD-10495",
      sentiment: Sentiment.NEG,
      sentimentScore: -0.72,
      status: FeedbackStatus.REVIEWED,
      daysAgo: 4,
      themeKeys: ["onboarding"],
    },
    {
      channel: "SUPPORT_TICKET",
      content: "Our Okta SAML SSO setup fails with an invalid callback URL error after your weekend maintenance update.",
      customerLabel: "Enterprise Tier",
      sourceRef: "ZD-10501",
      sentiment: Sentiment.NEG,
      sentimentScore: -0.91,
      status: FeedbackStatus.ACTIONED,
      daysAgo: 5,
      themeKeys: ["security"],
    },
    {
      channel: "SUPPORT_TICKET",
      content: "How can I set up automated webhooks so our internal engineering Slack receives new customer feedback immediately?",
      customerLabel: "Pro SaaS Tier",
      sourceRef: "ZD-10512",
      sentiment: Sentiment.NEU,
      sentimentScore: 0.1,
      status: FeedbackStatus.NEW,
      daysAgo: 7,
      themeKeys: ["integrations"],
    },
    {
      channel: "SUPPORT_TICKET",
      content: "The CSV export button is completely missing in the new dashboard view. We need this for our weekly executive meeting.",
      customerLabel: "SMB Tier",
      sourceRef: "ZD-10520",
      sentiment: Sentiment.NEG,
      sentimentScore: -0.65,
      status: FeedbackStatus.REVIEWED,
      daysAgo: 9,
      themeKeys: ["analytics"],
    },
    {
      channel: "SUPPORT_TICKET",
      content: "Customer success rep helped us resolve our webhook payload formatting in under 10 minutes. Fantastic support!",
      customerLabel: "Scaleup Corp",
      sourceRef: "ZD-10528",
      sentiment: Sentiment.POS,
      sentimentScore: 0.92,
      status: FeedbackStatus.ACTIONED,
      daysAgo: 11,
      themeKeys: ["integrations"],
    },
    {
      channel: "SUPPORT_TICKET",
      content: "Credit card payment failed with 'card_declined' but our bank confirms no charge attempt was received.",
      customerLabel: "Pro Tier",
      sourceRef: "ZD-10534",
      sentiment: Sentiment.NEG,
      sentimentScore: -0.78,
      status: FeedbackStatus.NEW,
      daysAgo: 13,
      themeKeys: ["billing"],
    },
    {
      channel: "SUPPORT_TICKET",
      content: "Need to transfer workspace ownership from our former CTO to our current VP of Engineering. Please assist.",
      customerLabel: "Enterprise Tier",
      sourceRef: "ZD-10540",
      sentiment: Sentiment.NEU,
      sentimentScore: 0.05,
      status: FeedbackStatus.ACTIONED,
      daysAgo: 15,
      themeKeys: ["security", "onboarding"],
    },
    {
      channel: "SUPPORT_TICKET",
      content: "The API rate limit of 60 req/min is too restrictive for our nightly CRM sync. Can we upgrade to a dedicated quota?",
      customerLabel: "FinTech Scaleup",
      sourceRef: "ZD-10547",
      sentiment: Sentiment.NEU,
      sentimentScore: -0.2,
      status: FeedbackStatus.REVIEWED,
      daysAgo: 17,
      themeKeys: ["integrations", "performance"],
    },
    {
      channel: "SUPPORT_TICKET",
      content: "Two-factor authentication SMS codes are delayed by 5-10 minutes, causing login sessions to expire repeatedly.",
      customerLabel: "HealthTech Plus",
      sourceRef: "ZD-10555",
      sentiment: Sentiment.NEG,
      sentimentScore: -0.88,
      status: FeedbackStatus.NEW,
      daysAgo: 19,
      themeKeys: ["security"],
    },
    {
      channel: "SUPPORT_TICKET",
      content: "Can we get custom invoice billing with Net-30 payment terms instead of automatic credit card billing?",
      customerLabel: "Mid-Market",
      sourceRef: "ZD-10562",
      sentiment: Sentiment.NEU,
      sentimentScore: 0.0,
      status: FeedbackStatus.NEW,
      daysAgo: 21,
      themeKeys: ["billing"],
    },
    {
      channel: "SUPPORT_TICKET",
      content: "Dashboard loads noticeably faster since last week's patch! Filtering across 10,000 items is virtually instant.",
      customerLabel: "Enterprise Tier",
      sourceRef: "ZD-10570",
      sentiment: Sentiment.POS,
      sentimentScore: 0.88,
      status: FeedbackStatus.ACTIONED,
      daysAgo: 23,
      themeKeys: ["performance"],
    },
    {
      channel: "SUPPORT_TICKET",
      content: "User permissions are unclear: Can Analysts generate executive Voice-of-Customer reports or only Admins?",
      customerLabel: "Pro SaaS Tier",
      sourceRef: "ZD-10578",
      sentiment: Sentiment.NEU,
      sentimentScore: -0.1,
      status: FeedbackStatus.REVIEWED,
      daysAgo: 25,
      themeKeys: ["security"],
    },
    {
      channel: "SUPPORT_TICKET",
      content: "Database sync disconnected after our PostgreSQL password was rotated. Reconnect button threw a 500 error.",
      customerLabel: "Enterprise Tier",
      sourceRef: "ZD-10585",
      sentiment: Sentiment.NEG,
      sentimentScore: -0.75,
      status: FeedbackStatus.ACTIONED,
      daysAgo: 27,
      themeKeys: ["integrations", "performance"],
    },
    {
      channel: "SUPPORT_TICKET",
      content: "We accidentally deleted our Q2 feedback theme. Is there a soft-delete restore capability in the audit log?",
      customerLabel: "Mid-Market",
      sourceRef: "ZD-10592",
      sentiment: Sentiment.NEG,
      sentimentScore: -0.62,
      status: FeedbackStatus.NEW,
      daysAgo: 29,
      themeKeys: ["features"],
    },
    {
      channel: "SUPPORT_TICKET",
      content: "Weekly digest report email was sent to all workspace members, including external contractors. Need tighter privacy controls.",
      customerLabel: "Enterprise Tier",
      sourceRef: "ZD-10601",
      sentiment: Sentiment.NEG,
      sentimentScore: -0.82,
      status: FeedbackStatus.ACTIONED,
      daysAgo: 31,
      themeKeys: ["security", "analytics"],
    },
    {
      channel: "SUPPORT_TICKET",
      content: "Very satisfied with the migration support from our old Zendesk feedback tool to LOOP. The team was responsive.",
      customerLabel: "Scaleup Corp",
      sourceRef: "ZD-10610",
      sentiment: Sentiment.POS,
      sentimentScore: 0.94,
      status: FeedbackStatus.ACTIONED,
      daysAgo: 33,
      themeKeys: ["onboarding"],
    },
    {
      channel: "SUPPORT_TICKET",
      content: "Search index took over 4 hours to re-index after bulk uploading our historical CSV customer feedback.",
      customerLabel: "Pro Tier",
      sourceRef: "ZD-10618",
      sentiment: Sentiment.NEG,
      sentimentScore: -0.58,
      status: FeedbackStatus.REVIEWED,
      daysAgo: 35,
      themeKeys: ["performance"],
    },
    {
      channel: "SUPPORT_TICKET",
      content: "Where do we find our workspace API key for pushing telemetry directly from our backend node servers?",
      customerLabel: "Dev Team Lead",
      sourceRef: "ZD-10624",
      sentiment: Sentiment.NEU,
      sentimentScore: 0.0,
      status: FeedbackStatus.REVIEWED,
      daysAgo: 37,
      themeKeys: ["integrations"],
    },
    {
      channel: "SUPPORT_TICKET",
      content: "Subscription upgrade from Starter to Pro was billed twice on our Mastercard statement. Please refund duplicate charge.",
      customerLabel: "SMB Tier",
      sourceRef: "ZD-10632",
      sentiment: Sentiment.NEG,
      sentimentScore: -0.92,
      status: FeedbackStatus.ACTIONED,
      daysAgo: 39,
      themeKeys: ["billing"],
    },
    {
      channel: "SUPPORT_TICKET",
      content: "Is there an option to configure data retention policies to automatically purge customer feedback older than 365 days?",
      customerLabel: "Legal & Compliance",
      sourceRef: "ZD-10640",
      sentiment: Sentiment.NEU,
      sentimentScore: 0.15,
      status: FeedbackStatus.NEW,
      daysAgo: 41,
      themeKeys: ["security"],
    },
    {
      channel: "SUPPORT_TICKET",
      content: "The interactive chart hover tooltip in the analytics tab overlaps with the navigation sidebar on smaller 13-inch displays.",
      customerLabel: "Pro SaaS Tier",
      sourceRef: "ZD-10649",
      sentiment: Sentiment.NEG,
      sentimentScore: -0.45,
      status: FeedbackStatus.NEW,
      daysAgo: 43,
      themeKeys: ["analytics"],
    },
    {
      channel: "SUPPORT_TICKET",
      content: "App runs smoothly during our high-traffic product launch. Handled 3,000 incoming support survey rows without a hiccup.",
      customerLabel: "Enterprise Tier",
      sourceRef: "ZD-10657",
      sentiment: Sentiment.POS,
      sentimentScore: 0.89,
      status: FeedbackStatus.ACTIONED,
      daysAgo: 45,
      themeKeys: ["performance"],
    },
    {
      channel: "SUPPORT_TICKET",
      content: "Our team invites are bouncing for emails containing plus-addressing (e.g., user+loop@company.com).",
      customerLabel: "Pro Tier",
      sourceRef: "ZD-10665",
      sentiment: Sentiment.NEG,
      sentimentScore: -0.52,
      status: FeedbackStatus.REVIEWED,
      daysAgo: 47,
      themeKeys: ["onboarding"],
    },
    {
      channel: "SUPPORT_TICKET",
      content: "Can we request a dedicated account manager to help train our product operations analysts on AI theme clustering?",
      customerLabel: "Enterprise Tier",
      sourceRef: "ZD-10672",
      sentiment: Sentiment.POS,
      sentimentScore: 0.65,
      status: FeedbackStatus.ACTIONED,
      daysAgo: 49,
      themeKeys: ["features"],
    },
    {
      channel: "SUPPORT_TICKET",
      content: "Password reset emails were delayed by 30 minutes during today's login incident.",
      customerLabel: "SMB Tier",
      sourceRef: "ZD-10680",
      sentiment: Sentiment.NEG,
      sentimentScore: -0.71,
      status: FeedbackStatus.ACTIONED,
      daysAgo: 51,
      themeKeys: ["security"],
    },
    {
      channel: "SUPPORT_TICKET",
      content: "The dark mode color palette is easy on the eyes during late night triage shifts. Much appreciated!",
      customerLabel: "Analyst Lead",
      sourceRef: "ZD-10688",
      sentiment: Sentiment.POS,
      sentimentScore: 0.81,
      status: FeedbackStatus.ACTIONED,
      daysAgo: 53,
      themeKeys: ["features"],
    },
    {
      channel: "SUPPORT_TICKET",
      content: "Cannot change the workspace currency from USD to EUR for our European subsidiary.",
      customerLabel: "EU Operations",
      sourceRef: "ZD-10695",
      sentiment: Sentiment.NEG,
      sentimentScore: -0.48,
      status: FeedbackStatus.NEW,
      daysAgo: 55,
      themeKeys: ["billing"],
    },
    {
      channel: "SUPPORT_TICKET",
      content: "Prompt engineering team wants to know if Claude system instructions can be customized per workspace.",
      customerLabel: "AI Ops Team",
      sourceRef: "ZD-10702",
      sentiment: Sentiment.NEU,
      sentimentScore: 0.2,
      status: FeedbackStatus.REVIEWED,
      daysAgo: 57,
      themeKeys: ["features"],
    },
    {
      channel: "SUPPORT_TICKET",
      content: "Exporting Voice-of-Customer executive digest to PDF generates a clean printable document without clipping. Great job!",
      customerLabel: "Enterprise Tier",
      sourceRef: "ZD-10710",
      sentiment: Sentiment.POS,
      sentimentScore: 0.95,
      status: FeedbackStatus.ACTIONED,
      daysAgo: 59,
      themeKeys: ["analytics"],
    },

    // --- APP STORE REVIEWS (25 items) ---
    {
      channel: "APP_STORE",
      content: "The new dashboard is gorgeous and finally fast. Huge improvement over the previous version!",
      customerLabel: "iOS User (v2.4)",
      sourceRef: "AS-REV-9831",
      sentiment: Sentiment.POS,
      sentimentScore: 0.93,
      status: FeedbackStatus.ACTIONED,
      daysAgo: 1,
      themeKeys: ["mobile", "performance"],
    },
    {
      channel: "APP_STORE",
      content: "FaceID login fails on iOS 17. Every time I open the app I have to type in my 20-character password manually.",
      customerLabel: "iOS User (v2.4)",
      sourceRef: "AS-REV-9835",
      sentiment: Sentiment.NEG,
      sentimentScore: -0.84,
      status: FeedbackStatus.NEW,
      daysAgo: 3,
      themeKeys: ["mobile", "security"],
    },
    {
      channel: "APP_STORE",
      content: "Great product for reviewing customer feedback on the train, but it really needs an iPad split-screen layout.",
      customerLabel: "iPad Pro User",
      sourceRef: "AS-REV-9842",
      sentiment: Sentiment.NEU,
      sentimentScore: 0.35,
      status: FeedbackStatus.REVIEWED,
      daysAgo: 6,
      themeKeys: ["mobile"],
    },
    {
      channel: "APP_STORE",
      content: "Push notifications for negative sentiment alerts stopped firing after yesterday's update.",
      customerLabel: "Android User (v2.3)",
      sourceRef: "GP-REV-4102",
      sentiment: Sentiment.NEG,
      sentimentScore: -0.79,
      status: FeedbackStatus.NEW,
      daysAgo: 8,
      themeKeys: ["mobile"],
    },
    {
      channel: "APP_STORE",
      content: "Super clean interface and zero bloat. Love being able to triage customer feedback during my morning commute.",
      customerLabel: "iOS User (v2.4)",
      sourceRef: "AS-REV-9850",
      sentiment: Sentiment.POS,
      sentimentScore: 0.91,
      status: FeedbackStatus.ACTIONED,
      daysAgo: 10,
      themeKeys: ["mobile"],
    },
    {
      channel: "APP_STORE",
      content: "App crashes immediately on launch when opening large VoC reports with complex charts.",
      customerLabel: "Pixel 8 Pro",
      sourceRef: "GP-REV-4115",
      sentiment: Sentiment.NEG,
      sentimentScore: -0.92,
      status: FeedbackStatus.NEW,
      daysAgo: 12,
      themeKeys: ["mobile", "performance"],
    },
    {
      channel: "APP_STORE",
      content: "Offline mode is desperately needed. If I lose cellular in the subway, the inbox goes completely blank.",
      customerLabel: "iOS User",
      sourceRef: "AS-REV-9861",
      sentiment: Sentiment.NEG,
      sentimentScore: -0.67,
      status: FeedbackStatus.REVIEWED,
      daysAgo: 14,
      themeKeys: ["mobile"],
    },
    {
      channel: "APP_STORE",
      content: "The biometric fingerprint login on Samsung Galaxy S24 is buttery smooth. Well done developers!",
      customerLabel: "Samsung S24 User",
      sourceRef: "GP-REV-4128",
      sentiment: Sentiment.POS,
      sentimentScore: 0.87,
      status: FeedbackStatus.ACTIONED,
      daysAgo: 16,
      themeKeys: ["mobile", "security"],
    },
    {
      channel: "APP_STORE",
      content: "Font size in feedback cards is slightly too small and doesn't respect iOS Dynamic Type accessibility settings.",
      customerLabel: "iOS User (v2.3)",
      sourceRef: "AS-REV-9875",
      sentiment: Sentiment.NEU,
      sentimentScore: -0.25,
      status: FeedbackStatus.REVIEWED,
      daysAgo: 18,
      themeKeys: ["mobile"],
    },
    {
      channel: "APP_STORE",
      content: "Best customer feedback tool on mobile. Our entire executive team has it installed for real-time sentiment alerts.",
      customerLabel: "CPO Review",
      sourceRef: "AS-REV-9884",
      sentiment: Sentiment.POS,
      sentimentScore: 0.96,
      status: FeedbackStatus.ACTIONED,
      daysAgo: 20,
      themeKeys: ["mobile", "analytics"],
    },
    {
      channel: "APP_STORE",
      content: "Battery drain is excessive when leaving the analytics dashboard open in the background.",
      customerLabel: "iPhone 15 User",
      sourceRef: "AS-REV-9892",
      sentiment: Sentiment.NEG,
      sentimentScore: -0.74,
      status: FeedbackStatus.NEW,
      daysAgo: 22,
      themeKeys: ["mobile", "performance"],
    },
    {
      channel: "APP_STORE",
      content: "Can we get home screen lock-screen widgets showing daily feedback volume and sentiment score?",
      customerLabel: "iOS User (v2.4)",
      sourceRef: "AS-REV-9901",
      sentiment: Sentiment.POS,
      sentimentScore: 0.62,
      status: FeedbackStatus.REVIEWED,
      daysAgo: 26,
      themeKeys: ["mobile", "features"],
    },
    {
      channel: "APP_STORE",
      content: "Filtering works smoothly on tablet. It's so convenient to filter by negative sentiment and share direct quotes.",
      customerLabel: "Tablet User",
      sourceRef: "GP-REV-4140",
      sentiment: Sentiment.POS,
      sentimentScore: 0.85,
      status: FeedbackStatus.ACTIONED,
      daysAgo: 28,
      themeKeys: ["mobile"],
    },
    {
      channel: "APP_STORE",
      content: "Logging in via Google SSO keeps giving error 400 redirect_uri_mismatch on Android.",
      customerLabel: "Android User",
      sourceRef: "GP-REV-4155",
      sentiment: Sentiment.NEG,
      sentimentScore: -0.81,
      status: FeedbackStatus.NEW,
      daysAgo: 32,
      themeKeys: ["mobile", "security"],
    },
    {
      channel: "APP_STORE",
      content: "The Ask LOOP search bar on mobile answers questions with impressive precision and quotes real customers.",
      customerLabel: "iOS User (v2.3)",
      sourceRef: "AS-REV-9915",
      sentiment: Sentiment.POS,
      sentimentScore: 0.94,
      status: FeedbackStatus.ACTIONED,
      daysAgo: 34,
      themeKeys: ["mobile", "analytics"],
    },
    {
      channel: "APP_STORE",
      content: "Pull-to-refresh sometimes stutters and duplicates items in the list until restarting the app.",
      customerLabel: "iOS User",
      sourceRef: "AS-REV-9922",
      sentiment: Sentiment.NEG,
      sentimentScore: -0.59,
      status: FeedbackStatus.REVIEWED,
      daysAgo: 36,
      themeKeys: ["mobile", "performance"],
    },
    {
      channel: "APP_STORE",
      content: "In-app notifications are clear and informative. Never spammy. Exactly what a mobile SaaS companion should be.",
      customerLabel: "Product Manager",
      sourceRef: "GP-REV-4168",
      sentiment: Sentiment.POS,
      sentimentScore: 0.88,
      status: FeedbackStatus.ACTIONED,
      daysAgo: 40,
      themeKeys: ["mobile"],
    },
    {
      channel: "APP_STORE",
      content: "Dark mode turns pure black into weird gray tones on OLED screens. Please adopt true pitch black #000.",
      customerLabel: "iOS User",
      sourceRef: "AS-REV-9938",
      sentiment: Sentiment.NEU,
      sentimentScore: -0.15,
      status: FeedbackStatus.NEW,
      daysAgo: 42,
      themeKeys: ["mobile"],
    },
    {
      channel: "APP_STORE",
      content: "Charts in the mobile analytics tab take over 8 seconds to render on 4G LTE connections.",
      customerLabel: "Android User",
      sourceRef: "GP-REV-4180",
      sentiment: Sentiment.NEG,
      sentimentScore: -0.68,
      status: FeedbackStatus.REVIEWED,
      daysAgo: 46,
      themeKeys: ["mobile", "performance"],
    },
    {
      channel: "APP_STORE",
      content: "The ability to mark items as REVIEWED or ACTIONED right from mobile push notifications is brilliant.",
      customerLabel: "Lead Analyst",
      sourceRef: "AS-REV-9945",
      sentiment: Sentiment.POS,
      sentimentScore: 0.92,
      status: FeedbackStatus.ACTIONED,
      daysAgo: 48,
      themeKeys: ["mobile"],
    },
    {
      channel: "APP_STORE",
      content: "Support team responded to my review within an hour and pushed a hotfix the next day. 5 stars for customer care.",
      customerLabel: "Scaleup Founder",
      sourceRef: "GP-REV-4192",
      sentiment: Sentiment.POS,
      sentimentScore: 0.97,
      status: FeedbackStatus.ACTIONED,
      daysAgo: 50,
      themeKeys: ["mobile"],
    },
    {
      channel: "APP_STORE",
      content: "Would be great if the mobile app supported multiple workspace switching without logging out and back in.",
      customerLabel: "Agency Consultant",
      sourceRef: "AS-REV-9952",
      sentiment: Sentiment.NEU,
      sentimentScore: 0.25,
      status: FeedbackStatus.NEW,
      daysAgo: 52,
      themeKeys: ["mobile", "onboarding"],
    },
    {
      channel: "APP_STORE",
      content: "Landscape orientation on iPad displays a black box over the sentiment breakdown donut chart.",
      customerLabel: "iPad User",
      sourceRef: "AS-REV-9960",
      sentiment: Sentiment.NEG,
      sentimentScore: -0.73,
      status: FeedbackStatus.REVIEWED,
      daysAgo: 54,
      themeKeys: ["mobile", "analytics"],
    },
    {
      channel: "APP_STORE",
      content: "Very lightweight app footprint — only 24MB install size. Fast download and instant startup.",
      customerLabel: "iOS User",
      sourceRef: "AS-REV-9971",
      sentiment: Sentiment.POS,
      sentimentScore: 0.86,
      status: FeedbackStatus.ACTIONED,
      daysAgo: 56,
      themeKeys: ["mobile", "performance"],
    },
    {
      channel: "APP_STORE",
      content: "Feedback submission form on mobile doesn't validate character limits until hitting submit.",
      customerLabel: "Beta Tester",
      sourceRef: "GP-REV-4205",
      sentiment: Sentiment.NEU,
      sentimentScore: -0.3,
      status: FeedbackStatus.NEW,
      daysAgo: 58,
      themeKeys: ["mobile"],
    },

    // --- NPS / CSAT SURVEYS (25 items) ---
    {
      channel: "NPS_SURVEY",
      content: "NPS 8/10: It does the job, but the mobile experience needs work. Web version is top-notch.",
      customerLabel: "Enterprise Cohort Q3",
      sourceRef: "NPS-CSAT-1001",
      sentiment: Sentiment.NEU,
      sentimentScore: 0.3,
      status: FeedbackStatus.REVIEWED,
      daysAgo: 2,
      themeKeys: ["mobile"],
    },
    {
      channel: "NPS_SURVEY",
      content: "NPS 10/10: Love the executive VoC summary reports. Saved our VP of Product hours of manual slide preparation.",
      customerLabel: "Pro SaaS Cohort",
      sourceRef: "NPS-CSAT-1004",
      sentiment: Sentiment.POS,
      sentimentScore: 0.95,
      status: FeedbackStatus.ACTIONED,
      daysAgo: 4,
      themeKeys: ["analytics"],
    },
    {
      channel: "NPS_SURVEY",
      content: "NPS 3/10: Constant 504 errors on invoice downloads make billing reconciliation a nightmare for our finance team.",
      customerLabel: "SMB Cohort",
      sourceRef: "NPS-CSAT-1009",
      sentiment: Sentiment.NEG,
      sentimentScore: -0.89,
      status: FeedbackStatus.NEW,
      daysAgo: 5,
      themeKeys: ["billing", "performance"],
    },
    {
      channel: "NPS_SURVEY",
      content: "NPS 9/10: The automatic Claude theme clustering has completely transformed how our sprint planning prioritizes bugs.",
      customerLabel: "Enterprise Cohort Q3",
      sourceRef: "NPS-CSAT-1015",
      sentiment: Sentiment.POS,
      sentimentScore: 0.91,
      status: FeedbackStatus.ACTIONED,
      daysAgo: 7,
      themeKeys: ["features"],
    },
    {
      channel: "NPS_SURVEY",
      content: "NPS 5/10: We need deeper Jira integration so triaged feedback cards can be converted into engineering stories directly.",
      customerLabel: "Tech Scaleup",
      sourceRef: "NPS-CSAT-1022",
      sentiment: Sentiment.NEU,
      sentimentScore: -0.1,
      status: FeedbackStatus.REVIEWED,
      daysAgo: 10,
      themeKeys: ["integrations"],
    },
    {
      channel: "NPS_SURVEY",
      content: "NPS 10/10: The Ask LOOP grounded Q&A is like having an analyst query 10,000 customer tickets instantly with zero hallucination.",
      customerLabel: "Product Lead",
      sourceRef: "NPS-CSAT-1028",
      sentiment: Sentiment.POS,
      sentimentScore: 0.98,
      status: FeedbackStatus.ACTIONED,
      daysAgo: 12,
      themeKeys: ["analytics"],
    },
    {
      channel: "NPS_SURVEY",
      content: "NPS 4/10: Onboarding wizard skipped team role configuration, resulting in our interns seeing sensitive billing data.",
      customerLabel: "Healthcare Cohort",
      sourceRef: "NPS-CSAT-1033",
      sentiment: Sentiment.NEG,
      sentimentScore: -0.82,
      status: FeedbackStatus.ACTIONED,
      daysAgo: 15,
      themeKeys: ["onboarding", "security"],
    },
    {
      channel: "NPS_SURVEY",
      content: "NPS 9/10: Fast, reliable, and beautifully designed. One of the rare enterprise tools that is actually enjoyable to use.",
      customerLabel: "Scaleup Founder",
      sourceRef: "NPS-CSAT-1040",
      sentiment: Sentiment.POS,
      sentimentScore: 0.93,
      status: FeedbackStatus.ACTIONED,
      daysAgo: 17,
      themeKeys: ["performance"],
    },
    {
      channel: "NPS_SURVEY",
      content: "NPS 6/10: Satisfactory tool, but we are waiting for webhook support before we can migrate all our Zendesk tickets.",
      customerLabel: "Mid-Market",
      sourceRef: "NPS-CSAT-1047",
      sentiment: Sentiment.NEU,
      sentimentScore: 0.15,
      status: FeedbackStatus.REVIEWED,
      daysAgo: 20,
      themeKeys: ["integrations"],
    },
    {
      channel: "NPS_SURVEY",
      content: "NPS 2/10: Unexpected 40% price increase on renewal without prior notice from our account manager.",
      customerLabel: "Enterprise Tier",
      sourceRef: "NPS-CSAT-1052",
      sentiment: Sentiment.NEG,
      sentimentScore: -0.94,
      status: FeedbackStatus.NEW,
      daysAgo: 23,
      themeKeys: ["billing"],
    },
    {
      channel: "NPS_SURVEY",
      content: "NPS 10/10: The multi-tenant security architecture and role-based permissions give our ISO compliance team total confidence.",
      customerLabel: "Security Officer",
      sourceRef: "NPS-CSAT-1061",
      sentiment: Sentiment.POS,
      sentimentScore: 0.96,
      status: FeedbackStatus.ACTIONED,
      daysAgo: 25,
      themeKeys: ["security"],
    },
    {
      channel: "NPS_SURVEY",
      content: "NPS 7/10: Good analytics, but please add multi-attribute filtering so I can view negative reviews from the App Store only.",
      customerLabel: "CX Analyst",
      sourceRef: "NPS-CSAT-1068",
      sentiment: Sentiment.NEU,
      sentimentScore: 0.25,
      status: FeedbackStatus.REVIEWED,
      daysAgo: 28,
      themeKeys: ["analytics"],
    },
    {
      channel: "NPS_SURVEY",
      content: "NPS 3/10: Performance in the Asia-Pacific region is sluggish compared to US East servers. Latency over 800ms.",
      customerLabel: "APAC Region User",
      sourceRef: "NPS-CSAT-1074",
      sentiment: Sentiment.NEG,
      sentimentScore: -0.77,
      status: FeedbackStatus.NEW,
      daysAgo: 30,
      themeKeys: ["performance"],
    },
    {
      channel: "NPS_SURVEY",
      content: "NPS 9/10: Customer support resolved our invoice billing confusion within 15 minutes. Best in class.",
      customerLabel: "Pro SaaS Tier",
      sourceRef: "NPS-CSAT-1081",
      sentiment: Sentiment.POS,
      sentimentScore: 0.9,
      status: FeedbackStatus.ACTIONED,
      daysAgo: 33,
      themeKeys: ["billing"],
    },
    {
      channel: "NPS_SURVEY",
      content: "NPS 8/10: Bulk CSV uploader saved us days of manual data entry when ingesting our historical survey responses.",
      customerLabel: "Product Operations",
      sourceRef: "NPS-CSAT-1089",
      sentiment: Sentiment.POS,
      sentimentScore: 0.85,
      status: FeedbackStatus.ACTIONED,
      daysAgo: 36,
      themeKeys: ["onboarding"],
    },
    {
      channel: "NPS_SURVEY",
      content: "NPS 5/10: The status lifecycle from NEW to ACTIONED is good, but would love automated email notifications when status changes.",
      customerLabel: "Mid-Market",
      sourceRef: "NPS-CSAT-1095",
      sentiment: Sentiment.NEU,
      sentimentScore: 0.05,
      status: FeedbackStatus.REVIEWED,
      daysAgo: 38,
      themeKeys: ["features"],
    },
    {
      channel: "NPS_SURVEY",
      content: "NPS 2/10: The dashboard was inaccessible for nearly 4 hours during last Tuesday's database maintenance window.",
      customerLabel: "Enterprise Tier",
      sourceRef: "NPS-CSAT-1102",
      sentiment: Sentiment.NEG,
      sentimentScore: -0.91,
      status: FeedbackStatus.ACTIONED,
      daysAgo: 41,
      themeKeys: ["performance"],
    },
    {
      channel: "NPS_SURVEY",
      content: "NPS 10/10: Being able to drill down from a trending spike directly into matching feedback quotes is game-changing.",
      customerLabel: "VP of Product",
      sourceRef: "NPS-CSAT-1110",
      sentiment: Sentiment.POS,
      sentimentScore: 0.97,
      status: FeedbackStatus.ACTIONED,
      daysAgo: 44,
      themeKeys: ["analytics", "features"],
    },
    {
      channel: "NPS_SURVEY",
      content: "NPS 4/10: We need granular SAML role mapping so our Okta groups map directly to ADMIN, ANALYST, and VIEWER.",
      customerLabel: "IT Director",
      sourceRef: "NPS-CSAT-1118",
      sentiment: Sentiment.NEG,
      sentimentScore: -0.65,
      status: FeedbackStatus.NEW,
      daysAgo: 47,
      themeKeys: ["security"],
    },
    {
      channel: "NPS_SURVEY",
      content: "NPS 9/10: The clean dark-mode design reduces eye strain during our weekly 2-hour feedback review sessions.",
      customerLabel: "Lead Designer",
      sourceRef: "NPS-CSAT-1125",
      sentiment: Sentiment.POS,
      sentimentScore: 0.88,
      status: FeedbackStatus.ACTIONED,
      daysAgo: 49,
      themeKeys: ["features"],
    },
    {
      channel: "NPS_SURVEY",
      content: "NPS 6/10: Exporting reports to PDF works well, but we need raw JSON export for downstream data pipelines.",
      customerLabel: "Data Scientist",
      sourceRef: "NPS-CSAT-1132",
      sentiment: Sentiment.NEU,
      sentimentScore: 0.2,
      status: FeedbackStatus.REVIEWED,
      daysAgo: 52,
      themeKeys: ["analytics", "integrations"],
    },
    {
      channel: "NPS_SURVEY",
      content: "NPS 1/10: Multiple unauthorized charge attempts appeared on our card after upgrading tiers. Very alarming.",
      customerLabel: "SMB Owner",
      sourceRef: "NPS-CSAT-1140",
      sentiment: Sentiment.NEG,
      sentimentScore: -0.97,
      status: FeedbackStatus.ACTIONED,
      daysAgo: 54,
      themeKeys: ["billing", "security"],
    },
    {
      channel: "NPS_SURVEY",
      content: "NPS 10/10: Intuitive UI, solid API, and the AI classification correctly flags 95% of our sentiment automatically.",
      customerLabel: "Head of CX",
      sourceRef: "NPS-CSAT-1148",
      sentiment: Sentiment.POS,
      sentimentScore: 0.95,
      status: FeedbackStatus.ACTIONED,
      daysAgo: 56,
      themeKeys: ["features"],
    },
    {
      channel: "NPS_SURVEY",
      content: "NPS 5/10: Needs better documentation on how sentiment scores are calculated between -1.0 and +1.0.",
      customerLabel: "Analytics Specialist",
      sourceRef: "NPS-CSAT-1155",
      sentiment: Sentiment.NEU,
      sentimentScore: 0.0,
      status: FeedbackStatus.NEW,
      daysAgo: 58,
      themeKeys: ["analytics"],
    },
    {
      channel: "NPS_SURVEY",
      content: "NPS 8/10: Great progress over the last two quarters. The app feels much more mature and stable.",
      customerLabel: "Enterprise Cohort Q1",
      sourceRef: "NPS-CSAT-1162",
      sentiment: Sentiment.POS,
      sentimentScore: 0.82,
      status: FeedbackStatus.ACTIONED,
      daysAgo: 60,
      themeKeys: ["performance"],
    },

    // --- SALES & SUCCESS CALL NOTES (25 items) ---
    {
      channel: "SALES_NOTE",
      content: "Prospect wants SAML SSO and SOC2 Type II report before they will sign — third time this month from Enterprise leads.",
      customerLabel: "Prospect: FinCorp ($60k ARR)",
      sourceRef: "CRM-DEAL-301",
      sentiment: Sentiment.NEG,
      sentimentScore: -0.68,
      status: FeedbackStatus.REVIEWED,
      daysAgo: 2,
      themeKeys: ["security"],
    },
    {
      channel: "SALES_NOTE",
      content: "Prospect was blown away by Ask LOOP grounded retrieval during live demo. Stated it was far superior to generic ChatGPT bots.",
      customerLabel: "Prospect: MedGlobal ($45k ARR)",
      sourceRef: "CRM-DEMO-305",
      sentiment: Sentiment.POS,
      sentimentScore: 0.94,
      status: FeedbackStatus.ACTIONED,
      daysAgo: 3,
      themeKeys: ["analytics"],
    },
    {
      channel: "SALES_NOTE",
      content: "Churn risk alert: Customer CTO indicated they will churn next quarter unless we support direct Snowflake data warehouse sync.",
      customerLabel: "Account: CloudMatrix ($36k ARR)",
      sourceRef: "CRM-CALL-312",
      sentiment: Sentiment.NEG,
      sentimentScore: -0.86,
      status: FeedbackStatus.NEW,
      daysAgo: 6,
      themeKeys: ["integrations"],
    },
    {
      channel: "SALES_NOTE",
      content: "Expansion discussion: Customer wants to purchase 25 additional Analyst seats if we add custom team workspace tagging.",
      customerLabel: "Account: RetailGiant ($80k ARR)",
      sourceRef: "CRM-DEAL-320",
      sentiment: Sentiment.POS,
      sentimentScore: 0.85,
      status: FeedbackStatus.REVIEWED,
      daysAgo: 8,
      themeKeys: ["features"],
    },
    {
      channel: "SALES_NOTE",
      content: "Lost deal debrief: Prospect chose competitor because of LOOP's lack of automated Zapier workflow triggers.",
      customerLabel: "Lost Prospect: AdAgency Co",
      sourceRef: "CRM-LOST-328",
      sentiment: Sentiment.NEG,
      sentimentScore: -0.76,
      status: FeedbackStatus.ACTIONED,
      daysAgo: 11,
      themeKeys: ["integrations"],
    },
    {
      channel: "SALES_NOTE",
      content: "QBR with VP of CX: They reported a 40% reduction in customer escalation triage time using our theme spike alerts.",
      customerLabel: "Account: LogiTech ($50k ARR)",
      sourceRef: "CRM-QBR-335",
      sentiment: Sentiment.POS,
      sentimentScore: 0.92,
      status: FeedbackStatus.ACTIONED,
      daysAgo: 13,
      themeKeys: ["analytics", "features"],
    },
    {
      channel: "SALES_NOTE",
      content: "Procurement review: Legal requires EU data residency guarantees before signing the annual enterprise agreement.",
      customerLabel: "Prospect: EuroBank ($90k ARR)",
      sourceRef: "CRM-DEAL-342",
      sentiment: Sentiment.NEU,
      sentimentScore: -0.15,
      status: FeedbackStatus.NEW,
      daysAgo: 16,
      themeKeys: ["security"],
    },
    {
      channel: "SALES_NOTE",
      content: "Demo reaction: Prospect's Head of Support loved the simulated Zendesk ticket ingest capability for staging sandbox tests.",
      customerLabel: "Prospect: SaaSify ($28k ARR)",
      sourceRef: "CRM-DEMO-350",
      sentiment: Sentiment.POS,
      sentimentScore: 0.88,
      status: FeedbackStatus.ACTIONED,
      daysAgo: 19,
      themeKeys: ["onboarding"],
    },
    {
      channel: "SALES_NOTE",
      content: "Competitor intelligence: Gong.io is launching basic customer sentiment tags, but lacks grounded Q&A and theme clustering.",
      customerLabel: "Market Intel",
      sourceRef: "CRM-INTEL-357",
      sentiment: Sentiment.POS,
      sentimentScore: 0.7,
      status: FeedbackStatus.REVIEWED,
      daysAgo: 21,
      themeKeys: ["features"],
    },
    {
      channel: "SALES_NOTE",
      content: "Account health check: Customer complained that pricing page does not clearly specify that Viewer seats are free.",
      customerLabel: "Account: GrowthLabs",
      sourceRef: "CRM-CALL-365",
      sentiment: Sentiment.NEG,
      sentimentScore: -0.55,
      status: FeedbackStatus.REVIEWED,
      daysAgo: 24,
      themeKeys: ["billing"],
    },
    {
      channel: "SALES_NOTE",
      content: "VP of Product call: Stated that LOOP's automated VoC report is the centerpiece of their monthly board deck.",
      customerLabel: "Account: HealthPulse ($65k ARR)",
      sourceRef: "CRM-CALL-372",
      sentiment: Sentiment.POS,
      sentimentScore: 0.96,
      status: FeedbackStatus.ACTIONED,
      daysAgo: 27,
      themeKeys: ["analytics"],
    },
    {
      channel: "SALES_NOTE",
      content: "Security questionnaire: Customer infosec flagged need for detailed audit logs tracking every role change and data export.",
      customerLabel: "Prospect: InsurTech Ltd",
      sourceRef: "CRM-DEAL-380",
      sentiment: Sentiment.NEU,
      sentimentScore: -0.2,
      status: FeedbackStatus.NEW,
      daysAgo: 29,
      themeKeys: ["security"],
    },
    {
      channel: "SALES_NOTE",
      content: "Renewal discussion: Client requested a multi-year discount of 15% in exchange for a 3-year commitment.",
      customerLabel: "Account: CloudMatrix ($36k ARR)",
      sourceRef: "CRM-DEAL-388",
      sentiment: Sentiment.POS,
      sentimentScore: 0.6,
      status: FeedbackStatus.REVIEWED,
      daysAgo: 32,
      themeKeys: ["billing"],
    },
    {
      channel: "SALES_NOTE",
      content: "Customer success alert: The team's primary Analyst transitioned to a new role; requested refresher onboarding session.",
      customerLabel: "Account: MedGlobal",
      sourceRef: "CRM-CALL-395",
      sentiment: Sentiment.NEU,
      sentimentScore: 0.1,
      status: FeedbackStatus.ACTIONED,
      daysAgo: 35,
      themeKeys: ["onboarding"],
    },
    {
      channel: "SALES_NOTE",
      content: "Prospect objection: Worried that Claude AI API calls might expose their proprietary customer feedback to public LLM training.",
      customerLabel: "Prospect: DefenseTech ($120k ARR)",
      sourceRef: "CRM-DEAL-402",
      sentiment: Sentiment.NEG,
      sentimentScore: -0.75,
      status: FeedbackStatus.REVIEWED,
      daysAgo: 37,
      themeKeys: ["security"],
    },
    {
      channel: "SALES_NOTE",
      content: "Sales demo: Prospect specifically requested white-label branding on generated Voice-of-Customer PDF reports.",
      customerLabel: "Prospect: MediaAgency",
      sourceRef: "CRM-DEMO-410",
      sentiment: Sentiment.NEU,
      sentimentScore: 0.3,
      status: FeedbackStatus.NEW,
      daysAgo: 40,
      themeKeys: ["analytics", "features"],
    },
    {
      channel: "SALES_NOTE",
      content: "Contract signed! $75,000 ARR enterprise deal closed. Primary driver was the robust RBAC and multi-tenant isolation.",
      customerLabel: "Client: GlobalRetail ($75k ARR)",
      sourceRef: "CRM-WON-418",
      sentiment: Sentiment.POS,
      sentimentScore: 0.99,
      status: FeedbackStatus.ACTIONED,
      daysAgo: 43,
      themeKeys: ["security"],
    },
    {
      channel: "SALES_NOTE",
      content: "Support escalation from sales: Client's billing admin unable to update company tax ID on self-serve portal.",
      customerLabel: "Account: EuroBank",
      sourceRef: "CRM-CALL-425",
      sentiment: Sentiment.NEG,
      sentimentScore: -0.6,
      status: FeedbackStatus.ACTIONED,
      daysAgo: 45,
      themeKeys: ["billing"],
    },
    {
      channel: "SALES_NOTE",
      content: "Prospect call: Inquired whether we have native Salesforce Service Cloud connector in our Q4 roadmap.",
      customerLabel: "Prospect: AutoScale ($40k ARR)",
      sourceRef: "CRM-CALL-432",
      sentiment: Sentiment.NEU,
      sentimentScore: 0.15,
      status: FeedbackStatus.NEW,
      daysAgo: 48,
      themeKeys: ["integrations"],
    },
    {
      channel: "SALES_NOTE",
      content: "Quarterly review: Customer praised system uptime (100% over the last 90 days) during their peak Black Friday sales.",
      customerLabel: "Account: ShopMaster ($55k ARR)",
      sourceRef: "CRM-QBR-440",
      sentiment: Sentiment.POS,
      sentimentScore: 0.95,
      status: FeedbackStatus.ACTIONED,
      daysAgo: 50,
      themeKeys: ["performance"],
    },
    {
      channel: "SALES_NOTE",
      content: "Churn risk debrief: Mid-market client churned citing that mobile experience did not meet their field rep requirements.",
      customerLabel: "Churned: FieldWorks ($18k ARR)",
      sourceRef: "CRM-LOST-448",
      sentiment: Sentiment.NEG,
      sentimentScore: -0.88,
      status: FeedbackStatus.ACTIONED,
      daysAgo: 53,
      themeKeys: ["mobile"],
    },
    {
      channel: "SALES_NOTE",
      content: "Customer compliment: Product Operations team was able to onboard 40 customer service reps in an afternoon.",
      customerLabel: "Account: SupportCo",
      sourceRef: "CRM-CALL-455",
      sentiment: Sentiment.POS,
      sentimentScore: 0.91,
      status: FeedbackStatus.ACTIONED,
      daysAgo: 55,
      themeKeys: ["onboarding"],
    },
    {
      channel: "SALES_NOTE",
      content: "Pilot feedback: Customer analytics lead requested ability to save custom filtered inbox segment views.",
      customerLabel: "Pilot: DataCorp",
      sourceRef: "CRM-PILOT-462",
      sentiment: Sentiment.POS,
      sentimentScore: 0.65,
      status: FeedbackStatus.REVIEWED,
      daysAgo: 57,
      themeKeys: ["features", "analytics"],
    },
    {
      channel: "SALES_NOTE",
      content: "Enterprise tender requirement: Must provide disaster recovery RPO under 1 hour and RTO under 4 hours.",
      customerLabel: "RFP: GovTech Agency",
      sourceRef: "CRM-RFP-470",
      sentiment: Sentiment.NEU,
      sentimentScore: 0.0,
      status: FeedbackStatus.NEW,
      daysAgo: 59,
      themeKeys: ["security", "performance"],
    },
    {
      channel: "SALES_NOTE",
      content: "Executive sponsor meeting: CFO noted that LOOP's insights helped uncover billing friction that was costing 2% churn.",
      customerLabel: "Account: SaaSify ($28k ARR)",
      sourceRef: "CRM-CALL-478",
      sentiment: Sentiment.POS,
      sentimentScore: 0.96,
      status: FeedbackStatus.ACTIONED,
      daysAgo: 60,
      themeKeys: ["billing", "analytics"],
    },

    // --- COMMUNITY & SOCIAL POSTS (25 items) ---
    {
      channel: "COMMUNITY",
      content: "Love the new export feature, saved me an hour today! The CSV download is clean and well-structured.",
      customerLabel: "Discord Community",
      sourceRef: "DISCORD-MSG-882",
      sentiment: Sentiment.POS,
      sentimentScore: 0.92,
      status: FeedbackStatus.ACTIONED,
      daysAgo: 1,
      themeKeys: ["analytics"],
    },
    {
      channel: "COMMUNITY",
      content: "Is anyone else having issues with the dark mode toggle getting stuck on mobile Safari?",
      customerLabel: "User Forum",
      sourceRef: "FORUM-THREAD-142",
      sentiment: Sentiment.NEG,
      sentimentScore: -0.42,
      status: FeedbackStatus.NEW,
      daysAgo: 3,
      themeKeys: ["mobile"],
    },
    {
      channel: "COMMUNITY",
      content: "Just imported 1,000 customer survey responses via CSV. The row-by-row validation feedback is incredible.",
      customerLabel: "Discord Community",
      sourceRef: "DISCORD-MSG-895",
      sentiment: Sentiment.POS,
      sentimentScore: 0.94,
      status: FeedbackStatus.ACTIONED,
      daysAgo: 5,
      themeKeys: ["onboarding"],
    },
    {
      channel: "COMMUNITY",
      content: "Feature request: Can we get keyboard shortcuts (j/k navigation, 1/2/3 for status triage) in the inbox?",
      customerLabel: "User Forum",
      sourceRef: "FORUM-THREAD-155",
      sentiment: Sentiment.POS,
      sentimentScore: 0.75,
      status: FeedbackStatus.REVIEWED,
      daysAgo: 7,
      themeKeys: ["features"],
    },
    {
      channel: "COMMUNITY",
      content: "The grounded Q&A in Ask LOOP is honestly witchcraft. It quoted a customer review from 3 weeks ago verbatim.",
      customerLabel: "Twitter / X Post",
      sourceRef: "X-POST-9021",
      sentiment: Sentiment.POS,
      sentimentScore: 0.97,
      status: FeedbackStatus.ACTIONED,
      daysAgo: 9,
      themeKeys: ["analytics"],
    },
    {
      channel: "COMMUNITY",
      content: "Why is there no webhook documentation in the developer portal? Took me two hours to reverse engineer the payload.",
      customerLabel: "Discord Community",
      sourceRef: "DISCORD-MSG-912",
      sentiment: Sentiment.NEG,
      sentimentScore: -0.74,
      status: FeedbackStatus.REVIEWED,
      daysAgo: 12,
      themeKeys: ["integrations"],
    },
    {
      channel: "COMMUNITY",
      content: "Has anyone managed to connect LOOP with Linear? Would love to auto-create issues for negative bug reports.",
      customerLabel: "User Forum",
      sourceRef: "FORUM-THREAD-168",
      sentiment: Sentiment.NEU,
      sentimentScore: 0.2,
      status: FeedbackStatus.NEW,
      daysAgo: 14,
      themeKeys: ["integrations"],
    },
    {
      channel: "COMMUNITY",
      content: "Shoutout to the engineering team for the 99.99% uptime this month. The app has been rock solid.",
      customerLabel: "LinkedIn Post",
      sourceRef: "LI-POST-304",
      sentiment: Sentiment.POS,
      sentimentScore: 0.95,
      status: FeedbackStatus.ACTIONED,
      daysAgo: 16,
      themeKeys: ["performance"],
    },
    {
      channel: "COMMUNITY",
      content: "Can we get custom webhook secret signing so our security team can verify HMAC signatures on incoming events?",
      customerLabel: "Discord Community",
      sourceRef: "DISCORD-MSG-928",
      sentiment: Sentiment.NEU,
      sentimentScore: 0.1,
      status: FeedbackStatus.REVIEWED,
      daysAgo: 18,
      themeKeys: ["security", "integrations"],
    },
    {
      channel: "COMMUNITY",
      content: "The billing breakdown doesn't explain proration charges when upgrading from 5 to 10 seats mid-cycle.",
      customerLabel: "User Forum",
      sourceRef: "FORUM-THREAD-180",
      sentiment: Sentiment.NEG,
      sentimentScore: -0.63,
      status: FeedbackStatus.NEW,
      daysAgo: 21,
      themeKeys: ["billing"],
    },
    {
      channel: "COMMUNITY",
      content: "Tips for solo founders: LOOP's weekly Voice-of-Customer summary is basically an AI product manager in a box.",
      customerLabel: "Product Hunt Discussion",
      sourceRef: "PH-THREAD-512",
      sentiment: Sentiment.POS,
      sentimentScore: 0.98,
      status: FeedbackStatus.ACTIONED,
      daysAgo: 23,
      themeKeys: ["analytics"],
    },
    {
      channel: "COMMUNITY",
      content: "Getting intermittent CORS errors when hitting the feedback ingestion API from our client-side feedback widget.",
      customerLabel: "Discord Community",
      sourceRef: "DISCORD-MSG-945",
      sentiment: Sentiment.NEG,
      sentimentScore: -0.7,
      status: FeedbackStatus.REVIEWED,
      daysAgo: 26,
      themeKeys: ["integrations", "security"],
    },
    {
      channel: "COMMUNITY",
      content: "Would love a Figma plugin that surfaces relevant customer quotes directly next to UI design mockups.",
      customerLabel: "User Forum",
      sourceRef: "FORUM-THREAD-195",
      sentiment: Sentiment.POS,
      sentimentScore: 0.82,
      status: FeedbackStatus.NEW,
      daysAgo: 28,
      themeKeys: ["features"],
    },
    {
      channel: "COMMUNITY",
      content: "The response time on large datasets went from 4.2 seconds to 350ms after the database migration. Tremendous!",
      customerLabel: "Discord Community",
      sourceRef: "DISCORD-MSG-960",
      sentiment: Sentiment.POS,
      sentimentScore: 0.93,
      status: FeedbackStatus.ACTIONED,
      daysAgo: 31,
      themeKeys: ["performance"],
    },
    {
      channel: "COMMUNITY",
      content: "Our team invites are occasionally marked as spam by Outlook / Office 365 spam filters.",
      customerLabel: "User Forum",
      sourceRef: "FORUM-THREAD-210",
      sentiment: Sentiment.NEG,
      sentimentScore: -0.58,
      status: FeedbackStatus.REVIEWED,
      daysAgo: 33,
      themeKeys: ["onboarding"],
    },
    {
      channel: "COMMUNITY",
      content: "Huge fan of the role-based access control. Allows our junior interns to triage without risking workspace settings.",
      customerLabel: "LinkedIn Post",
      sourceRef: "LI-POST-412",
      sentiment: Sentiment.POS,
      sentimentScore: 0.91,
      status: FeedbackStatus.ACTIONED,
      daysAgo: 36,
      themeKeys: ["security"],
    },
    {
      channel: "COMMUNITY",
      content: "Does LOOP support multi-language feedback classification? We have French and Spanish customer tickets coming in.",
      customerLabel: "Discord Community",
      sourceRef: "DISCORD-MSG-975",
      sentiment: Sentiment.NEU,
      sentimentScore: 0.25,
      status: FeedbackStatus.NEW,
      daysAgo: 38,
      themeKeys: ["features"],
    },
    {
      channel: "COMMUNITY",
      content: "Chart animations in the analytics dashboard are super fluid on high refresh rate monitors (120Hz).",
      customerLabel: "User Forum",
      sourceRef: "FORUM-THREAD-224",
      sentiment: Sentiment.POS,
      sentimentScore: 0.87,
      status: FeedbackStatus.ACTIONED,
      daysAgo: 41,
      themeKeys: ["analytics"],
    },
    {
      channel: "COMMUNITY",
      content: "The CSV uploader failed silently on a 15MB file because of an unhandled request body limit. Please add a warning!",
      customerLabel: "Discord Community",
      sourceRef: "DISCORD-MSG-988",
      sentiment: Sentiment.NEG,
      sentimentScore: -0.76,
      status: FeedbackStatus.REVIEWED,
      daysAgo: 44,
      themeKeys: ["onboarding", "performance"],
    },
    {
      channel: "COMMUNITY",
      content: "Really appreciate how the team builds in public and listens to community feature requests. Rare in B2B SaaS.",
      customerLabel: "Twitter / X Post",
      sourceRef: "X-POST-9150",
      sentiment: Sentiment.POS,
      sentimentScore: 0.96,
      status: FeedbackStatus.ACTIONED,
      daysAgo: 46,
      themeKeys: ["features"],
    },
    {
      channel: "COMMUNITY",
      content: "The color contrast on some inactive tab labels fails WCAG AA standards in light mode.",
      customerLabel: "User Forum",
      sourceRef: "FORUM-THREAD-238",
      sentiment: Sentiment.NEU,
      sentimentScore: -0.3,
      status: FeedbackStatus.NEW,
      daysAgo: 49,
      themeKeys: ["features"],
    },
    {
      channel: "COMMUNITY",
      content: "Can we get an RSS or Atom feed of public Voice-of-Customer changelogs to share with our end users?",
      customerLabel: "Discord Community",
      sourceRef: "DISCORD-MSG-1002",
      sentiment: Sentiment.POS,
      sentimentScore: 0.7,
      status: FeedbackStatus.NEW,
      daysAgo: 51,
      themeKeys: ["features", "analytics"],
    },
    {
      channel: "COMMUNITY",
      content: "Lost 10 minutes of filter settings because refreshing the page reset all dropdowns. Please sync filters to URL params!",
      customerLabel: "User Forum",
      sourceRef: "FORUM-THREAD-250",
      sentiment: Sentiment.NEG,
      sentimentScore: -0.65,
      status: FeedbackStatus.REVIEWED,
      daysAgo: 54,
      themeKeys: ["analytics"],
    },
    {
      channel: "COMMUNITY",
      content: "The simulated channel button made it so easy to demo LOOP to our executive committee before connecting production data.",
      customerLabel: "LinkedIn Post",
      sourceRef: "LI-POST-520",
      sentiment: Sentiment.POS,
      sentimentScore: 0.94,
      status: FeedbackStatus.ACTIONED,
      daysAgo: 57,
      themeKeys: ["onboarding"],
    },
    {
      channel: "COMMUNITY",
      content: "Zero regrets choosing LOOP over building an internal sentiment tracker. Saved our team months of custom LLM glue code.",
      customerLabel: "Twitter / X Post",
      sourceRef: "X-POST-9280",
      sentiment: Sentiment.POS,
      sentimentScore: 0.98,
      status: FeedbackStatus.ACTIONED,
      daysAgo: 60,
      themeKeys: ["features", "analytics"],
    },
  ];

  console.log(`✓ Preparing to seed ${rawDataset.length} realistic feedback items for Acme SaaS...`);

  // Insert feedback items and associate with themes via FeedbackTheme join table
  let createdCount = 0;
  for (const item of rawDataset) {
    const createdFeedback = await prisma.feedback.create({
      data: {
        content: item.content,
        channel: item.channel,
        customerLabel: item.customerLabel,
        sourceRef: item.sourceRef,
        sentiment: item.sentiment,
        sentimentScore: item.sentimentScore,
        status: item.status,
        workspaceId: acmeWorkspace.id,
        createdAt: getPastDate(item.daysAgo, (createdCount % 24)),
      },
    });

    // Create theme links
    for (const themeKey of item.themeKeys) {
      const themeId = themes[themeKey];
      if (themeId) {
        await prisma.feedbackTheme.create({
          data: {
            feedbackId: createdFeedback.id,
            themeId: themeId,
            confidence: Number((0.85 + Math.random() * 0.14).toFixed(2)),
          },
        });
      }
    }

    createdCount++;
  }

  console.log(`✓ Successfully seeded ${createdCount} feedback items with theme links for Acme SaaS`);

  // 6. Seed 10 feedback items for Beta Retail (for tenant isolation verification)
  const retailFeedbackItems = [
    { content: "Barcode scanner disconnects from register 3 during peak shopping hours.", channel: "SUPPORT_TICKET", sourceRef: "RET-001" },
    { content: "POS terminal receipt printer runs out of paper without warning.", channel: "SUPPORT_TICKET", sourceRef: "RET-002" },
    { content: "Inventory sync between warehouse and retail stores took 3 hours to reflect.", channel: "SUPPORT_TICKET", sourceRef: "RET-003" },
    { content: "Cashiers love the new quick-touch lookup on the touchscreens.", channel: "COMMUNITY", sourceRef: "RET-004" },
    { content: "Payment terminal contactless NFC tap works instantly with Apple Pay.", channel: "APP_STORE", sourceRef: "RET-005" },
    { content: "Credit card reader froze during checkout, forcing manual card entry.", channel: "SUPPORT_TICKET", sourceRef: "RET-006" },
    { content: "NPS 9/10: In-store checkout speed is significantly faster this holiday season.", channel: "NPS_SURVEY", sourceRef: "RET-007" },
    { content: "Store manager requested automated end-of-day cash reconciliation report.", channel: "SALES_NOTE", sourceRef: "RET-008" },
    { content: "Gift card balance lookup throws network timeout error intermittently.", channel: "SUPPORT_TICKET", sourceRef: "RET-009" },
    { content: "Offline checkout queue saved 40 transactions during the store internet outage.", channel: "COMMUNITY", sourceRef: "RET-010" },
  ];

  for (const item of retailFeedbackItems) {
    const feedback = await prisma.feedback.create({
      data: {
        content: item.content,
        channel: item.channel,
        customerLabel: "Retail Storefront",
        sourceRef: item.sourceRef,
        sentiment: Sentiment.NEU,
        sentimentScore: 0.0,
        status: FeedbackStatus.NEW,
        workspaceId: betaWorkspace.id,
        createdAt: getPastDate(3),
      },
    });

    await prisma.feedbackTheme.create({
      data: {
        feedbackId: feedback.id,
        themeId: retailTheme.id,
        confidence: 0.9,
      },
    });
  }
  console.log(`✓ Seeded ${retailFeedbackItems.length} isolation verification items for Beta Retail`);

  // 7. Verify and Print Summary Statistics
  const acmeFeedbackTotal = await prisma.feedback.count({
    where: { workspaceId: acmeWorkspace.id },
  });
  const betaFeedbackTotal = await prisma.feedback.count({
    where: { workspaceId: betaWorkspace.id },
  });
  const totalThemes = await prisma.theme.count();
  const totalUsers = await prisma.user.count();

  console.log("\n========================================================");
  console.log("🎉 PROJECT LOOP SEED COMPLETE — VERIFICATION STATS");
  console.log("========================================================");
  console.log(`Total Workspaces: 2 (Acme SaaS Demo + Beta Retail Isolation)`);
  console.log(`Total Users:      ${totalUsers} (Admin, Analyst, Viewer)`);
  console.log(`Total Themes:     ${totalThemes}`);
  console.log(`Acme Feedback:    ${acmeFeedbackTotal} (Requirement: >= 120 items) -> PASS!`);
  console.log(`Beta Feedback:    ${betaFeedbackTotal} (Isolated tenant items)`);
  console.log(`Global Feedback:  ${acmeFeedbackTotal + betaFeedbackTotal}`);
  console.log("========================================================\n");
}

main()
  .catch((e) => {
    console.error("❌ Seed failed:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
